name: rimlines
description: RimLines app flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_messaging: ^7.0.3
  dio: ^3.0.10
  hive: ^1.4.4+1
  hive_flutter: ^0.3.1
  bloc: ^6.1.1
  flutter_bloc: ^6.1.1
  flutter_spinkit: ^4.1.2+1
  shared_preferences: ^0.5.12+4
  url_launcher: ^5.7.10
  connectivity: ^2.0.2
  cached_network_image: ^2.4.1
  path_provider: ^1.6.24
  location: ^3.1.0
  font_awesome_flutter: ^8.11.0
  easy_localization: ^2.3.3
  flutter_secure_storage: ^3.3.5
  curved_navigation_bar: ^0.3.7
  google_fonts: 1.1.2
  get: ^3.26.0

  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/translations/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
