name: rimlines
description: RimLines app flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # FIERBASE
  firebase_messaging: ^9.1.2

  # STORAGE RELATED
  path_provider: ^2.0.1
  hive: ^2.0.4
  hive_flutter: ^1.0.0
  shared_preferences: ^2.0.5
  flutter_secure_storage: ^4.1.0

  # STATE MANAGEMENT
  bloc: ^7.0.0
  flutter_bloc: ^7.0.0

  # TOOLS
  get: ^4.1.4
  http: ^0.13.1
  connectivity: ^3.0.3
  url_launcher: ^6.0.3
  location: ^4.1.1
  easy_localization: ^3.0.0

  # GRAPHIC RELATED
  flutter_spinkit: ^5.0.0
  font_awesome_flutter: ^9.0.0
  google_fonts: ^2.0.0
  curved_navigation_bar: ^0.3.7

  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/translations/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
